#!/usr/bin/python3
j=__import__('apt-gui')
pkgs=j.pkgs
main=j.main
env=j.env

if env.check("EXTRAINSTALL"):
    pkgs.extend((
"waterfox-kde",
"keepassxc",
"transmission-gtk",
"xreader",
"valent"
))

pkgs.extend((
#"adwaita-qt5",
#"adwaita-qt6",
"adwaita-xfce-icon-theme",
"NetworkManager-gnome",
"dbus-1-daemon",
"geany",
"gtk2-metatheme-adwaita",
"gtk3-metatheme-adwaita",
#"gtk4-metatheme-adwaita",
#"epiphany",
#"evolution",
"gnome-themes-extras",
"gvfs",
"gvfs-backends",
"gvfs-fuse",
#"keepassxc",
"labwc",
'polkit-gnome',
"menulibre",
"mugshot",
"kvantum-manager",
"kvantum-qt5",
"kvantum-qt6",
#"qt5ct",
#"qt6ct",
"eog",
"vlc",
"sddm-qt6",
"sfwbar",
"thunar",
"thunar-archive-plugin",
"thunar-volman",
"xfce4-desktop",
"xfce4-notifyd",
"xfce4-panel",
"xfce4-power-manager",
"xfce4-pulseaudio-plugin",
"xfce4-session",
"xfce4-settings",
"xfce4-settings-color",
"xfce4-terminal",
"xfce4-whiskermenu-plugin",
"xfce4-screenshooter",
"xfce4-taskmanager",
"xfwm4",
"xwayland"
))

if __name__ == '__main__': 
    main()
