#!/usr/bin/python3
j=__import__('apt-gui')
pkgs=j.pkgs
main=j.main
env=j.env

if env.check("EXTRAINSTALL"):
    pkgs.extend((
"secrets",
"transmission-gtk",
"xreader",
"valent",
"seahorse",
"fractal"
))

pkgs.extend((
"adwaita-qt5",
"adwaita-qt6",
"adwaita-xfce-icon-theme",
"NetworkManager-gnome",
"dbus-1-daemon",
"geany",
#"epiphany",
#"evolution",
"gnome-themes-extras",
"gvfs",
"gvfs-backends",
"gvfs-fuse",
#"keepassxc",
"labwc",
'polkit-gnome',
"menulibre",
"mugshot",
"qt5ct",
"qt6ct",
"eog",
"parole",
"lightdm-slick-greeter",
"sfwbar",
"thunar",
"thunar-archive-plugin",
"thunar-volman",
"xfce4-desktop",
"xfce4-notifyd",
"xfce4-panel",
"xfce4-power-manager",
"xfce4-pulseaudio-plugin",
"xfce4-session",
"xfce4-settings",
"xfce4-settings-color",
"xfce4-terminal",
"xfce4-whiskermenu-plugin",
"xfce4-screenshooter",
"xfce4-taskmanager",
"xfwm4",
"xwayland",
'gnome-keyring-pam',
'gtk4-metatheme-yaru-mate',
'gtk3-metatheme-yaru-mate',
'gtk2-metatheme-yaru-mate'
))

if __name__ == '__main__': 
    main()
