#!/usr/bin/python3
j=__import__('apt-gui')
pkgs=j.pkgs
main=j.main

pkgs.extend((
"adwaita-qt5",
"adwaita-qt6",
"adwaita-xfce-icon-theme",
"NetworkManager-gnome",
"dbus-1-daemon",
"gtk2-metatheme-adwaita",
"gtk3-metatheme-adwaita",
#"gtk4-metatheme-adwaita",
#"epiphany",
#"evolution",
"gnome-themes-extras",
"gvfs",
"gvfs-backends",
"gvfs-fuse",
#"keepassxc",
"labwc",
"menulibre",
"mugshot",
"qt5ct",
"qt6ct",
"sddm-qt6",
"sfwbar",
"thunar",
"thunar-archive-plugin",
"thunar-volman",
"xfce4-desktop",
"xfce4-notifyd",
"xfce4-panel",
"xfce4-power-manager",
"xfce4-session",
"xfce4-settings",
"xfce4-settings-color",
"xfce4-terminal",
"xfce4-whiskermenu-plugin",
"xfce4-screenshooter",
"xfce4-taskmanager",
"xfwm4",
"xwayland"
))

if __name__ == '__main__': 
    main()
