services:
  opensuse_systemd:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./:/extra/repo:rw
    tmpfs:
      - /run
      - /tmp
    stdin_open: true
    tty: true
    cgroup: host
    hostname: systemd-host
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
