# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'variant'
        default: 'gnome'
        required: true
        type: string
      env:
        description: 'environment variables, delimited with ;'
        default: 'GNOME_ANIMATIONS=yes ; EXTRAINSTALL=yes ; INSTALL_NEW_RECOMMENDS=yes'
        required: false
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout
      uses: actions/checkout@v4
    - name: Linux - Install apt dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: gh coreutils perl python3 systemd-container mtools bash zypper sed squashfs-tools xorriso
        version: 1.0
    - name: Refresh zypper cache
      run: |
        cd pacman
        sudo bash -x ./aptat.sh
        cd ../
        sudo zypper --gpg-auto-import-keys ref
    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1
      with:
        version: latest
    - name: Generate ISO
      run: |
        set -a
        export ENVIRONMENT=${{ github.event.inputs.env }}
        docker compose up --build --force-recreate
    - name: Upload ISO
      run: |
        mkdir deployment
        mv *.iso deployment
        TAG="${{ github.event.inputs.name }} $(date)"
        STAMP=`date +%s`
        gh release create "${STAMP}" deployment/*.iso --title "${TAG}" --notes "Initial release with assets."
